syntax = "All"
column_width = 120
indent_width = 2
indent_type = "Spaces"
quote_style = "ForceDouble"
call_parentheses = "Always"
block_newline_gaps = "Never"
collapse_simple_statement = "Never"
space_after_function_names = "Never"
# line_endings = "Unix"

[sort_requires]
enabled = true
